### PR TITLE
Let's see what we have and where

### LINKED ISSUE #3: Need to ship 7zip.dll for 7zip

### PR DESCRIPTION
**Pull request by yarikoptic**
If done, closes #3 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yarikoptic** [comment]
@wolfv done!  I see dll's being included and checked for dynlibraries, so I guess it should be all good! Please merge -- I am eager to try it out ;)

**Comment by wolfv** [comment]
Cool!

Do we also need the .lib files in case someone wants to link 7zip.dll?

**Comment by yarikoptic** [comment]
Oh, I have no clue in windows... May be? Would need to check what other packages do. If you merge as is, we could check first if it all works, and proceed with lib in follow up pr

**Comment by yarikoptic** [comment]
ok, seems to work
```
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
The system cannot find the path specified.
Bundles\Format7z\x64\7za.dll
        1 file(s) copied.
Bundles\Format7zExtract\x64\7zxa.dll
        1 file(s) copied.
Bundles\Format7zExtractR\x64\7zxr.dll
        1 file(s) copied.
Bundles\Format7zF\x64\7z.dll
        1 file(s) copied.
Bundles\Format7zR\x64\7zra.dll
        1 file(s) copied.
The system cannot find the path specified.
Bundles\Format7z\x64\7za.lib
        1 file(s) copied.
Bundles\Format7zExtract\x64\7zxa.lib
        1 file(s) copied.
Bundles\Format7zExtractR\x64\7zxr.lib
        1 file(s) copied.
Bundles\Format7zF\x64\7z.lib
        1 file(s) copied.
Bundles\Format7zR\x64\7zra.lib
        1 file(s) copied
```
although something is not found...  I will remove printing listing now... imho it is ready unless you see what else is needed/it wants.

**Comment by yarikoptic** [comment]
@wolfv AFAIK it is ready to be merged, with dlls and libs now

**Comment by wolfv** [comment]
yes, looks good! thanks!!

**Pull request merged**
